title: Prodziekan
description: "Trochę śmietnik, trochę stonka"
url: "https://prodziekan-yt.github.io"
baseurl: ""
remote_theme: "b2a3e8/jekyll-theme-console"
style: dark
lang: pl
header_pages:
  - index.md
  - blog.md
  - youtube.md
  - repo.md
